### ISSUE TITLE
Kexecboot download missing

### ISSUE THREAD

**Issue by sgargel** [danboid/ZALARM-install#1]
> To install kexecboot, download the tarball from the same page as the [Zaurus ALARM kernel downloads](https://github.com/greguu/linux-4.2.3-c3x00/releases)

but I' ve not found the kexecboot tarball there!

**Comment by danboid** [comment]
It's still there OK, its just that greg hasn't updated it since v0.2 so you have to use that version

https://github.com/greguu/linux-4.2.3-c3x00/releases/download/v0.2/arch-kexecboot.tar.xz
